Changes to support testing entirely within the UDx container environment
Add vsdk-vertica --- a script that starts a Vertica in a container
for you to test with.

Changed Dockerfile_RPM to build a container with a runnable Vertica inside
it (this is derived from the one-node-ce Dockerfile).

entrypoint.sh can handle the situation where it is invoked to run a Vertica.

diff --git a/UDx-container/vsdk-vertica b/UDx-container/vsdk-vertica
--- a/UDx-container/vsdk-vertica
+++ b/UDx-container/vsdk-vertica
@@ -14,11 +14,12 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# Since this script is a wrapper for other commands (which have their
-# own command-line arguments that we don't want to interfere with),
-# most of the option-setting for this script is done using environment
-# variables.
-#
+# Unlike the other vsdk-* commands, this command actually has
+# command-line arguments.
+
+# However, to be consistent with the other vsdk-* commands, it
+# understands the same environment variables they do.
+
 # For example, $OSTAG-$VERTICA_VERSION is used to define the container
 # tag (e.g., verticasdk:centos-11.0.0-0).  So, if you have multiple
 # verticavsdk containers lying around, you can select among them by
@@ -41,22 +42,15 @@
 #       the --env-file option of the "docker run" command, so the file
 #       needs to be formatted for that option
 
-PROG=`basename $0`
-
-# If you have multiple vsdk containers, you can
-# choose among them by specifying the tag, which
-# is derived from ${OSTAG}-${VERTICA_VERSION}, if those
-# variables are set in the environment.
-
 # The user can override the OS selection by defining OSTAG in the
 # environment (mostly for testing)
 . /etc/os-release
+
 case $ID in
     rhel) OSTAG=${OSTAG:=centos} ;;
     ubuntu) OSTAG=${OSTAG:=ubuntu} ;;
     *) OSTAG=${OSTAG:=centos} ;;
 esac
-
 case $OSTAG in
     centos)
         BINDIR=/usr/bin 
@@ -67,36 +61,13 @@ case $OSTAG in
         ALSO_IN_PATH=/usr/bin
         ;;
 esac
-V_VERSION=${VERTICA_VERSION:=11.0.0-0}
-CONTAINER_TAG=verticasdk:$OSTAG-$V_VERSION
-DVOL=verticasdk-data 
 
-INTERACTIVE=
-case $PROG in
-    vsdk-bash)
-        INTERACTIVE=-it
-        CMD=${BINDIR}/bash
-        ;;
-    vsdk-cp)
-        CMD=${BINDIR}/cp
-        ;;
-    vsdk-g++)
-        case $OSTAG in
-            centos)
-                CMD=/opt/rh/devtoolset-7/root/usr/bin/g++ ;;
-            ubuntu)
-                CMD=/usr/bin/g++ ;;
-        esac
-        ;;
-    vsdk-make)
-        CMD=/usr/bin/make
-        ;;
-    *)
-        echo Unknown vsdk-command: $PROG
-        echo Known commands: vsdk-make, vsdk-g++, vsdk-bash, vsdk-cp
-        exit 1
-        ;;
-esac
+V_VERSION=${VERTICA_VERSION:=11.0.0-0}
+IMAGE_NAME=verticasdk
+TAG=$OSTAG-$V_VERSION
+
+CONTAINER_NAME=verticasdk
+DVOL=verticasdk-data 
 
 VSDK_VOLUMES=""
 if [ "$VSDK_MOUNT"x != x ]; then
@@ -109,14 +80,6 @@ VSDK_ENV_FILE_OPTION=""
 if [ "$VSDK_ENV"x != x ]; then
     VSDK_ENV_FILE_OPTION="--env-file $VSDK_ENV"
 fi
-
-user_id=`id -u`
-HOSTNAME=vsdk-$USER
-
-#         --env LD_LIBRARY_PATH=/opt/vertica/lib 
-
-# this would be an include file, except I don't know how to find
-# the file if I'm in a different directory
 
 CONTAINER_PATH=/opt/rh/rh-nodejs8/root/usr/bin
 CONTAINER_PATH=$CONTAINER_PATH:/opt/rh/llvm-toolset-7.0/root/usr/bin
@@ -131,19 +94,72 @@ CONTAINER_PATH=$CONTAINER_PATH:/usr/sbin
 CONTAINER_PATH=$CONTAINER_PATH:/usr/local/bin
 CONTAINER_PATH=$CONTAINER_PATH:/usr/local/sbin
 
+user_id=`id -u`
+HOSTNAME=vsdk-$USER
 
+function usage_exit() {
+    cat <<EOF
+Usage: $0 [-c cname] [-h] [-i img_name] [-t tag] [-v hostpath:containerdir] [-V docker-volume]
+Options are:
+ -c - specify container name (default is $CONTAINER_NAME)
+ -h - show help
+ -i image - specify image name (default is $IMAGE_NAME)
+ -t tag - specify the image tag (default is $TAG)
+ -v hostpath:containerdir - mount hostpath as containerdir in the 
+        container (in addition to the data docker volume)
+ -V volume - docker volume to use for the Vertica database (default is $DVOL)
+EOF
+    exit $1
+}
+
+while getopts "c:d:hi:r:t:v:V:" opt; do
+    case "$opt" in
+        c) CONTAINER_NAME="${OPTARG}"
+           ;;
+        h) usage_exit 0
+           ;;
+        i) IMAGE_NAME=${OPTARG}
+           ;;
+        t) TAG="${OPTARG}"
+           ;;
+        v) VFLAG="-v ${OPTARG}"
+           ;;
+        V) DVOL="${OPTARG}"
+           ;;
+        \?) echo "Invalid option: -$OPTARG" >&2
+            echo
+            usage_exit 1
+            ;;
+    esac
+done
 CURDIR=`/bin/pwd`
+
+echo "Starting container..."
 docker run \
-       $INTERACTIVE \
+       --security-opt=seccomp:unconfined \
+       --privileged \
        -e PATH=$CONTAINER_PATH \
        -e vUID=$user_id \
        -e vUSER=$USER \
-       -u $user_id \
        -v "$HOME:$HOME:rw" \
-       -v $CURDIR:$CURDIR:rw \
-       --mount type=volume,source=$DVOL,target=/data \
+       -v ${CURDIR}:${CURDIR}:rw \
        $VSDK_VOLUMES \
        $VSDK_ENV_FILE_OPTION \
-       $CONTAINER_TAG \
-       $CURDIR \
-       "$CMD $*"
+       --mount type=volume,source=$DVOL,target=/data \
+       -p 5433:5433 \
+       -p 5444:5444 \
+       -d $VFLAG \
+       --name $CONTAINER_NAME \
+       $IMAGE_NAME:$TAG \
+       ${CURDIR} \
+       vertica
+echo
+
+echo
+echo "Run"
+echo "      docker logs $CONTAINER_NAME"
+echo "to view startup progress"
+echo
+echo "Don't stop container until above command prints 'Vertica is now running'"
+echo "To stop:"
+echo "    docker stop $CONTAINER_NAME"
