templates for vsdk-vertica & vsdk-exec (guess version)

diff --git a/UDx-container/vsdk-vertica.template b/UDx-container/vsdk-vertica.template
--- a/UDx-container/vsdk-vertica.template
+++ b/UDx-container/vsdk-vertica.template
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # -*- mode: shell-script -*-
 
-# (c) Copyright [2021] Micro Focus or one of its affiliates.
+# (c) Copyright [2021-2023] Open Text.
 # Licensed under the Apache License, Version 2.0 (the "License");
 # You may not use this file except in compliance with the License.
 # You may obtain a copy of the License at
@@ -14,15 +14,15 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# Unlike the other vsdk-* commands, this command actually has
+# Unlike the other wasmsdk-* commands, this command actually has
 # command-line arguments.
 
-# However, to be consistent with the other vsdk-* commands, it
+# However, to be consistent with the other wasmsdk-* commands, it
 # understands the same environment variables they do.
 
 # For example, $OSTAG-$VERTICA_VERSION is used to define the container
 # tag (e.g., verticasdk:centos-11.0.0-0).  So, if you have multiple
-# verticavsdk containers lying around, you can select among them by
+# verticawasmsdk containers lying around, you can select among them by
 # defining these variables in the environment.
 #
 # OSTAG: one of { centos, ubuntu } --- selects the container OS
@@ -33,12 +33,12 @@
 #
 # In addition, there is these environment variables:
 #
-# VSDK_MOUNT: an optional space-separated list of host directories to
+# WASMSDK_MOUNT: an optional space-separated list of host directories to
 #       mount in the UDx container --- that is, "I'm going to want to
 #       refer to files in these directories in, for example, my
 #       makefile, or as include directories in code to be compiled"
 #
-# VSDK_ENV: names a file filled with variable definitions.  This uses
+# WASMSDK_ENV: names a file filled with variable definitions.  This uses
 #       the --env-file option of the "docker run" command, so the file
 #       needs to be formatted for that option
 
@@ -51,13 +51,84 @@
 # conditions, plus simplify symlinks.
 # See https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel
 
+if [[ -z $VSDK_IMAGE ]]; then
+    if [[ -z $OSTAG ]]; then
+        # The user can default the OS selection by defining OSTAG in the
+        # environment (mostly for testing)
+        . /etc/os-release
+        
+        case $ID in
+            (rhel) OSTAG=centos ;;
+            (ubuntu) OSTAG=ubuntu ;;
+            (*) OSTAG=centos ;;
+        esac
+        WARNINGS+=("WARNING: Guessing OSTAG $OSTAG. Set VSDK_IMAGE to avoid this warning")
+    fi
+    
+    VERTICA_VERSION=${VERTICA_VERSION:++DEFAULT_VERTICA_VERSION++}
+    
+    if [[ -n $OSTAG && -n $VERTICA_VERSION ]]; then
+        VSDK_IMAGE=vertica/verticasdk:$OSTAG-v$VERTICA_VERSION
+    else
+        # Is there only one image?  Let's just print a warning.
+        VSDK_IMAGE=$(docker image ls vertica/verticasdk --format "{{.Repository}}:{{.Tag}}")
+        if [[ $VSDK_IMAGE =~ ^vertica/verticasdk:(centos|ubuntu)-v[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$ ]]; then
+            WARNINGS+=("WARNING: Using image $VSDK_IMAGE. Set VSDK_IMAGE to avoid this warning")
+        else
+            echo "ERROR: Set VSDK_IMAGE to vertica/verticasdk:<OSTAG>-v<VERTICA_VERSION>" >&2
+            exit 1
+        fi
+    fi
+fi
+
+case $OSTAG in
+    centos)
+        BINDIR=/usr/bin 
+        ALSO_IN_PATH=/bin
+        ;;
+    ubuntu)
+        BINDIR=/bin
+        ALSO_IN_PATH=/usr/bin
+        ;;
+esac
+
+
+SCRIPT_DIR="$( cd `dirname "${BASH_SOURCE[0]}"` &> /dev/null && pwd )"
+. ${SCRIPT_DIR}/set_container_path
+
+# we didn't error out, so print the warnings.
+for w in "${WARNINGS[@]}"; do echo $w >&2; done
+
+IMAGE_NAME=verticasdk
+TAG=$OSTAG-${VERTICA_VERSION:-++DEFAULT_VERTICA_VERSION++}
+
+CONTAINER_TAG=${CONTAINER_TAG:-vertica/verticasdk:$OSTAG-v${VERTICA_VERSION:-++DEFAULT_VERTICA_VERSION++}}
+DVOL=verticasdk-data 
+
+CONTAINER_NAME=verticasdk-vertica
+
+VSDK_VOLUMES=""
+if [ "$VSDK_MOUNT"x != x ]; then
+    for dir in $VSDK_MOUNT; do
+        VSDK_VOLUMES="$VSDK_VOLUMES -v $dir:$dir"
+    done
+fi
+
+VSDK_ENV_FILE_OPTION=""
+if [ "$VSDK_ENV"x != x ]; then
+    VSDK_ENV_FILE_OPTION="--env-file $VSDK_ENV"
+fi
+
+user_id=`id -u`
+
 function usage_exit() {
     cat <<EOF
 Usage: $0 [-c cname] [-h] [-i img_name] [-t tag] [-v hostpath:containerdir] [-V docker-volume]
 Options are:
- -c - specify container name
+ -c - specify container name (default is $CONTAINER_NAME)
  -h - show help
- -i image - specify image name
+ -i image - specify image name (default is $IMAGE_NAME)
+ -t tag - specify the image tag (default is $TAG)
  -v hostpath:containerdir - mount hostpath as containerdir in the 
         container (in addition to the data docker volume)
  -V volume - docker volume to use for the Vertica database (default is $DVOL)
@@ -89,77 +160,6 @@ CURDIR=`/bin/pwd`
 
 PORTOFFSET=$(( RANDOM % 10000 ))
 
-user_id=`id -u`
-user_name=`id -un`
-
-if [[ -z $OSTAG ]]; then
-    # The user can default the OS selection by defining OSTAG in the
-    # environment (mostly for testing)
-    . /etc/os-release
-
-    case $ID in
-        rhel)
-            OSTAG=centos 
-            ;;
-        ubuntu)
-            OSTAG=ubuntu 
-            ;;
-        *)
-            OSTAG=centos 
-            ;;
-    esac
-fi
-
-case $OSTAG in
-    centos)
-        BINDIR=/usr/bin 
-        ALSO_IN_PATH=/bin
-        ;;
-    ubuntu)
-        BINDIR=/bin
-        ALSO_IN_PATH=/usr/bin
-        ;;
-esac
-
-if [[ -z $VSDK_IMAGE ]]; then
-  IMAGE_NAME=vertica/verticasdk
-  TAG=$OSTAG-v${VERTICA_VERSION:-11.0.0-0}
-  VSDK_IMAGE=$IMAGE_NAME:$TAG
-fi
-
-CONTAINER_NAME=verticasdk-${user_name}
-DVOL=verticasdk-data-${user_name}
-
-VSDK_VOLUMES=""
-if [ "$VSDK_MOUNT"x != x ]; then
-    for dir in $VSDK_MOUNT; do
-        VSDK_VOLUMES="$VSDK_VOLUMES -v $dir:$dir"
-    done
-fi
-
-VSDK_ENV_FILE_OPTION=""
-if [[ ! -z $VSDK_ENV ]]; then
-    VSDK_ENV_FILE_OPTION="--env-file $VSDK_ENV"
-fi
-
-case $OSTAG in
-centos)     
-    CONTAINER_PATH=/opt/rh/rh-nodejs8/root/usr/bin
-    CONTAINER_PATH=$CONTAINER_PATH:/opt/rh/llvm-toolset-7.0/root/usr/bin
-    CONTAINER_PATH=$CONTAINER_PATH:/opt/rh/llvm-toolset-7.0/root/usr/sbin
-    CONTAINER_PATH=$CONTAINER_PATH:/opt/rh/rh-git218/root/usr/bin
-    CONTAINER_PATH=$CONTAINER_PATH:/opt/rh/devtoolset-7/root/usr/bin
-    ;;
-esac
-
-CONTAINER_PATH=$CONTAINER_PATH:/usr/lib64/ccache
-CONTAINER_PATH=$CONTAINER_PATH:${BINDIR}
-CONTAINER_PATH=$CONTAINER_PATH:${ALSO_IN_PATH}
-CONTAINER_PATH=$CONTAINER_PATH:/sbin
-CONTAINER_PATH=$CONTAINER_PATH:/usr/sbin
-CONTAINER_PATH=$CONTAINER_PATH:/usr/local/bin
-CONTAINER_PATH=$CONTAINER_PATH:/usr/local/sbin
-
 echo "Starting container..."
 if docker run \
        --security-opt=seccomp:unconfined \
@@ -169,16 +169,15 @@ if docker run \
        -e vUSER=$USER \
        -v "$HOME:$HOME:rw" \
        -v ${CURDIR}:${CURDIR}:rw \
-       -w "$PWD" \
        $VSDK_VOLUMES \
        $VSDK_ENV_FILE_OPTION \
-       --mount type=volume,source=$DVOL,target=/data \
+       --mount type=volume,source=$DVOL,target=/wasmdata \
        -p $(( PORTOFFSET + 5433 )):5433 \
        -p $(( PORTOFFSET + 5444 )):5444 \
        -d \
        $VFLAG \
        --name $CONTAINER_NAME \
-       $VSDK_IMAGE \
+       $CONTAINER_TAG \
        ${CURDIR} \
        vertica
 then
@@ -191,10 +190,10 @@ then
     echo "To stop:"
     echo "    docker stop $CONTAINER_NAME"
     echo
-    echo "When executing outside of a VSDK container, you can connect to this vertica"
+    echo "When executing outside of a VerticaSDK container, you can connect to this vertica"
     echo "using"
-    echo "    vsql -p $(( PORTOFFSET + 5433 ))" -U dbadmin
+    echo "    vsql -p $(( PORTOFFSET + 5433 ))"
     echo
-    echo "If executing inside a the VSDK container (e.g., using run-dbadmin-shell-in-container),"
+    echo "If executing inside a VerticaSDK container (where you did your Wasm development),"
     echo "just 'vsql' should suffice"
 fi
